/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package junit;

public class App {

    public static void main(String[] args) {
        System.out.println("Hello Wordl");
    }
}
